### ISSUE TITLE
Expected output: Att or tau?

### ISSUE THREAD

**Issue by karllark** [karllark/dust_attenuation#16]
Need to decide the output from the model. 
Attenuation (Att) in mags?
Optical depth (tau)?

**Comment by karllark** [comment]
I lean towards Att, but can see the motivation for tau.
What do others think?

We do provide the attenuate function for users just wanting to attenuate or un-attenuate their models/data.

**Comment by karllark** [comment]
Going to move forward on this soonish.  If I don't hear alternative proposals, we will go with Att(V).  Mainly as I think attenuation in mags is more common than attenuation in optical depth.  Especially in analogy to dust extinction curves where it is always A(V).

**Comment by dcorre** [comment]
For my own research I prefer to use Att(V) as it is more intuitive (correction in mag of the observations). I rarely see tau(V), except in papers dealing with radiative transfer, of course.
This could be the default output of the model and in the base class we need to define a method converting to tau(V)

**Comment by karllark** [comment]
Ok.  I will close this issue and make a new one that says convert WG00 from outputing tau to Att.
