### ISSUE TITLE
C00 and WG00 need tests for calculation

### ISSUE THREAD

**Issue by karllark** [karllark/dust_attenuation#19]
Tests need to check that actual calculation of the numbers for both C00 and WG00.  
Ideally, this would be against tables published in those papers.  Otherwise, calculations from another source.  Or even calculations with this code frozen so that at least we will know if something changes.

**Comment by dcorre** [comment]
It is on my To do list, I should be able to do it by the end of the month. I'm too busy at the moment.

I do not think there is a table for C00, but we can use the results of this code

For WG00, there are plenty of tables ;)

**Comment by karllark** [comment]
Sounds great!
