### ISSUE TITLE
WG00: move get_model code to initialize

### ISSUE THREAD

**Issue by karllark** [karllark/dust_attenuation#21]
Currently, the WG00 model has a two step initialization.  

First the model is initialized as normal.  Then the get_model function is called to load in the appropriate table given the model geometry, dust_type, and dust_distribution.

Why not have the get_model functionality in an explicit initialization step?  This would make it more like other models and reduce the number of initialization lines.
I have seen that this is possible in other implementations of astropy.modeling (can't find it right now, but could if this sounds like a good idea).

**Comment by dcorre** [comment]
Yes that's ugly, I haven't found the solution to load the model within an initialising step but I wanted to write a functional model within the short available time I had so I kept this solution.
I need to search what is equivalent to def __init__(self,...) for astropy.modeling classes
If you have an example it would be perfect.

**Comment by karllark** [comment]
It is possible to do a standard _init_ in a model.   Check out the astropy modeling code for polynomials.  Not quite sure all what needs doing, but it is possible.  Just need to figure out the details.  I can ask the experts at STScI early next week if that helps.

https://github.com/astropy/astropy/blob/master/astropy/modeling/polynomial.py

**Comment by dcorre** [comment]
Thanks for the link, I did not know about this super.__init__()
There is no need for the get_model initialisation step anymore. I'll make a pull request with the updated docs in 2 or 3 days.

**Comment by karllark** [comment]
Cool!
