### ISSUE TITLE
Organization of models

### ISSUE THREAD

**Issue by karllark** [karllark/dust_attenuation#24]
I am thinking that it would be better to not break things into one file per model as the imports look like:
from dust_attenuation.C00 import C00

Instead, how about having 3 files for each type of model? One for averages, one for radiative transfer mdoels, and one for shape fitting models. The base classes for each type of model could go into the appropriate file with, if needed, one more file with any generic code that is used by multiple types of models. The imports would then be:
from dust_attenuation.averages import C00
from dust_attenuation.radiative_transfer import WG00
from dust_attenuation.shapes import N09

Comments?

**Comment by dcorre** [comment]
Yes, one comment:  good idea! ;)

**Comment by karllark** [comment]
Ok.  Should I give it a try then?  I can put in a pull request today.  If you are working on WG00 or C00, then I can wait till you are done.  Otherwise, we will have conflicts and the merge will be harder.

**Comment by dcorre** [comment]
I just worked successfully on the WG00 initialisation, but I will not have time to change the corresponding documentation before Monday or Tuesday. So you can work on the models reorganisation.

**Comment by karllark** [comment]
Ok.  I can do this.  You will probably have to manually port your current changes to the WG00 initialization to a new branch once I update the master.  The filenames will change and I bet this will break things with your current work.  At least that is my expectation.  Just a FYI.

**Comment by dcorre** [comment]
I just made a test and it requires only a few changes that I haven't commited yet, so it is not a problem.

**Comment by karllark** [comment]
Great.  Pull request soon.
