### ISSUE TITLE
How to assess the quality of a fit performed by astropy.modeling.fitting?

### ISSUE THREAD

**Issue by dcorre** [karllark/dust_attenuation#32]
I am using LevMarLSQFitter and am trying to fit hundreds of attenuation curves automatically. Sometimes the fit failed. It is also sensitive to initial conditions, which is logical.

Hence my question: does anyone know how to assess the quality of a fit performed by astropy.modeling.fitting? 
If one fits only a few attenuation curves, one can still check by eye. However in a automatised process, one should rely on a criteria to assess the quality of the fit, for instance the chi2. There is still the solution to compute the chi2 myself but I can not believe that there is no such quantity to assess the quality of the fit provided by the package, though I haven't found it in the documentation yet.

With a nice fit quality assessment it will be possible to fix the sensitivity to the initial values, by running the fit with different initial conditions and keeping the best fit. Otherwise a MCMC algorithm could also fix the problem.

**Comment by karllark** [comment]
The whole topic of is the fit a good one is large and not well defined. I would go with a chisqr criteria as this is the basis of the LevMarLSQ fitter.  Definitely try different starting guesses and pick the one with the smallest chisqr.  

There is fit info returned, but you have to go to the scipy info page.
http://docs.astropy.org/en/stable/api/astropy.modeling.fitting.LevMarLSQFitter.html#astropy.modeling.fitting.LevMarLSQFitter
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.leastsq.html#scipy.optimize.leastsq

**Comment by karllark** [comment]
Note that MCMC algorithm can also get stuck in a local minimum, so trying different starting values is also needed.  I usually start my MCMC runs with the result of a standard chisqr minimization fit as recommended by the emcee authors.

**Comment by karllark** [comment]
Your MCMC solution sounds great.  Erik Tollerud mentioned the same method to me - distributing the initial emcee points around the allowed space based on the priors.  I haven't had time to try this yet.  I do wonder how well this works when one has lots of parameters and, thus, a vast parameter space to investigate.

**Comment by karllark** [comment]
Closing issue as I think this question was answered.  Feel free to tell me to open it again if more discussion is needed.  Or anything.
