### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by karllark** [karllark/dust_attenuation#35]
Not all the plots are showing up in the documentation.  This usually means there is some error making the plot.  Need to track down.
At least the L02 reference is missing from the naming convention page.  L02 plot is empty.
A few minor problems, just noting them here for cleanup at the appropriate time.

**Comment by karllark** [comment]
I did not see in in the references.

**Comment by dcorre** [comment]
sorry, I meant what do you call the L00 plot?

**Comment by karllark** [comment]
Sorry, meant L02.

http://dust-attenuation.readthedocs.io/en/latest/api/dust_attenuation.averages.L02.html#dust_attenuation.averages.L02

**Comment by dcorre** [comment]
The problem with the L02 plot was that in np.arange() the step in wavelength was 0.1 microns from 0.1 to 0.18 microns, resulting in one point only... now it is 0.01 microns. 

The L02 reference has been added to reference.rst in the new pull request.
