### ISSUE TITLE
Broken in Astropy 6.0.0

### ISSUE THREAD

**Issue by TheSkyentist** [karllark/dust_attenuation#54]
Code is broken in Astropy 6.0.0 due to deprecation in the [Configuration System](https://docs.astropy.org/en/stable/config/index.html) module (see Astropy issue [#11497](https://github.com/astropy/astropy/issues/11497))

Error that arises comes when the code attempts to import `update_default_config` which has been deprecated. 
https://github.com/karllark/dust_attenuation/blob/96cd27df7ed9b052797571eee1761b213e0bbaa0/dust_attenuation/_astropy_init.py#L23

Possible solutions are to:
a. Pin to astropy < 6.0.0 in `setup.cfg`.
b. Update to use updated interface. 

This also affects packages that use this as a dependency (e.g. [eazy](https://github.com/gbrammer/eazy-py) @gbrammer)

**Comment by karllark** [comment]
Yes, I've seen this issue in other repositories and the fix is straightforward.  Will put this on the todo list for today/tomorrow.

Great to hear this package is used by others.

**Comment by TheSkyentist** [comment]
Fantastic! Thanks for the quick response.
